[package]
name = "rust-actix-backend-engineering"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web="4"
serde={version ="1.0.197", features=["derive"]}
dotenv={version="0.15.0"}
diesel={version="2.2.0" features=["postgres"]}